In [2]:
#ONE DIMENSIONAL ARRAY

In [ ]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,56)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55])

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((58,36),int)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [13]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.linspace(1,2,6)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [16]:
np.linspace(23,56,12)

array([23., 26., 29., 32., 35., 38., 41., 44., 47., 50., 53., 56.])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.randn(2)

array([1.2077465 , 1.01645169])

In [23]:
np.random.rand(2,5)

array([[0.37022769, 0.07290222, 0.04398161, 0.65463433, 0.18149565],
       [0.14660036, 0.1574262 , 0.87329232, 0.95731719, 0.30399897]])

In [24]:
np.random.randint(5,36)

23

In [27]:
np.random.randint(36,400,125)

array([129,  83, 379, 271, 355, 114, 198, 380, 298,  72, 121, 119,  94,
       309, 183,  70, 369, 268, 180, 224,  40, 256,  50, 148, 283, 335,
       250, 254, 385, 280, 358, 211,  79, 301,  49, 311, 142,  59,  84,
       175, 219, 177, 203, 232, 190, 220, 394, 267, 309, 103, 194, 276,
       183, 332, 301, 392, 153,  77, 222,  73, 348, 277, 145, 101, 265,
       106, 292,  72, 349, 216, 227, 253, 300,  48,  80, 204, 202, 200,
       170, 227,  58, 362, 120, 367, 367, 131, 196, 314, 177,  65, 394,
       229, 377, 159, 211, 397, 292, 278, 248, 243, 257,  92, 292, 218,
       301,  94, 166, 163, 129, 219, 139, 281, 218, 114, 244, 391, 133,
       328, 323, 134, 381, 317, 249, 165, 193])

In [29]:
sample_array = np.arange(30)
print(sample_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [31]:
random_array = np.random.randint(0,100,20)
print(random_array)

[81 22 28 12  4 80 76 85 80 98 41  3 25 36  2  9 62 49 74 40]


In [32]:
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [38]:
sample_array.resize(3,10)
sample_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [39]:
random_array.min()

2

In [40]:
random_array.argmin()

14

In [41]:
random_array.max()

98

In [42]:
random_array.argmax()

9

In [44]:
sample_array.dtype

dtype('int64')

In [45]:
a=np.eye(6)

In [46]:
a.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [48]:
a=np.random.rand(3,2)
a

array([[0.50230481, 0.83184245],
       [0.94392207, 0.69955603],
       [0.5807806 , 0.25426716]])

In [49]:
a.T

array([[0.50230481, 0.94392207, 0.5807806 ],
       [0.83184245, 0.69955603, 0.25426716]])

In [ ]:
#TWO DIMENSIONAL ARRAY

In [52]:
sample_matrix = np.array(([1,5,9],[3,6,8],[2,4,7]))
sample_matrix

array([[1, 5, 9],
       [3, 6, 8],
       [2, 4, 7]])

In [54]:
sample_matrix[1][2]

8

In [57]:
sample_matrix[2,:]

array([2, 4, 7])

In [56]:
sample_matrix[1]

array([3, 6, 8])

In [58]:
sample_matrix[:,(2,1)]

array([[9, 5],
       [8, 6],
       [7, 4]])

In [59]:
#SELECTION TECHNIQUES

In [60]:
sample_array = np.arange(1,20)

In [61]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [62]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [63]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [64]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [65]:
np.max(sample_array)

19

In [66]:
np.min(sample_array)

1

In [67]:
np.argmax(sample_array)

18

In [68]:
np.argmin(sample_array)

0

In [69]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [70]:
np.std(sample_array)

5.477225575051661

In [71]:
np.var(sample_array)

30.0

In [72]:
np.mean(sample_array)

10.0

In [73]:
np.median(sample_array)

10.0

In [75]:
array = np.random.randn(3,4)
array

array([[ 0.70141588,  0.51956315,  0.80928457, -0.56506361],
       [ 2.41481721, -0.56880215,  1.55115703, -0.61159131],
       [ 1.03668763,  0.63643871, -0.3433651 , -0.31675536]])

In [76]:
np.round(array, decimals=4)

array([[ 0.7014,  0.5196,  0.8093, -0.5651],
       [ 2.4148, -0.5688,  1.5512, -0.6116],
       [ 1.0367,  0.6364, -0.3434, -0.3168]])

In [78]:
sports = np.array(['golf', 'cricket', 'fball', 'cricket', 'football'])
np.unique(sports)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')